"""
backend/app/main.py — FastAPI application entrypoint.

Run with:
    uvicorn backend.app.main:app --reload --port 8000

Then visit http://localhost:8000/docs for interactive API docs
(auto-generated by FastAPI — includes a working "Authorize" button
for testing the JWT-protected endpoints).
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.app.routers import auth, cases, health

app = FastAPI(
    title="SentinelScan API",
    description="Unified cross-platform malware detection & behavioral analysis suite — PS-4, E-Rakshak 2026",
    version="0.1.0-alpha",
)

# CORS — allows the React frontend (running on a different port during
# dev, e.g. localhost:5173) to call this API. Tighten allow_origins to
# the real deployed frontend URL before the live GCP deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(auth.router)
app.include_router(cases.router)


@app.get("/")
def root():
    return {"message": "SentinelScan API — see /docs for interactive documentation"}